//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loja
    {
        public int Id { get; set; }
        public string NomeLoja { get; set; }
        public string CNPJ { get; set; }
        public string RazaoSocial { get; set; }
        public int Telefone { get; set; }
        public string Proprietario { get; set; }
        public int TelefoneProprietario { get; set; }
    }
}
